services:
  # Основное приложение
  spectexpark:
    build: .
    container_name: spectexpark-app
    restart: unless-stopped
    ports:
      - "5100:80"
    volumes:
      - ./logs:/var/log/nginx
    environment:
      - NODE_ENV=production

networks:
  default:
    driver: bridge

volumes:
  logs:
